install.packages("tidyverse")
install.packages("dplyr")
install.packages("modeest")
install.packages("psych")
install.packages("https://cran.r-project.org/src/contrib/Archive/fdth/fdth_1.2-6.tar.gz", repo=NULL, type="source")
library(tidyverse)
library(dplyr)
library(modeest)
library(psych)